# Generated by Django 3.2.7 on 2021-09-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='contact',
        ),
        migrations.AddField(
            model_name='task',
            name='contact',
            field=models.ManyToManyField(to='base.Contact'),
        ),
    ]
