# Generated by Django 3.2.7 on 2021-09-10 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_auto_20210909_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Software',
        ),
        migrations.RemoveField(
            model_name='task',
            name='c_sharp',
        ),
        migrations.RemoveField(
            model_name='task',
            name='cpp',
        ),
        migrations.RemoveField(
            model_name='task',
            name='django',
        ),
        migrations.RemoveField(
            model_name='task',
            name='java',
        ),
        migrations.RemoveField(
            model_name='task',
            name='js',
        ),
        migrations.RemoveField(
            model_name='task',
            name='python',
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'user',
            },
        ),
    ]
