# Generated by Django 3.2.7 on 2021-09-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210910_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stack',
            field=models.ManyToManyField(to='base.Stack'),
        ),
    ]
